force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Комната</label>
    <nameField>
        <label>Номер комнаты</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Комнаты</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Available_Places__c.field-meta.xml
<CustomField>
    <fullName>Available_Places__c</fullName>
    <label>Доступно мест</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Вместимость</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Dormitory__c.field-meta.xml
<CustomField>
    <fullName>Dormitory__c</fullName>
    <label>Общежитие</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Комнаты</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Parent_Room__c.field-meta.xml
<CustomField>
    <fullName>Parent_Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Используется для создания вложенности блоков в комнату</description>
    <label>Родительская комната</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Комнаты</relationshipLabel>
    <relationshipName>Child_Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Пол жильцов</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/RoomSelectionController.cls
public with sharing class RoomSelectionController {
    @AuraEnabled
    public static List<Room__c> getAvailableRooms(String studentGender, Integer pageNumber, Integer pageSize) {
        Integer offset = (pageNumber - 1) * pageSize;

        Map<Id, Room__c> childRooms = new Map<Id, Room__c>([
            SELECT Id, Name, Available_Places__c, Capacity__c, Sex__c, Dormitory__r.Name, Parent_Room__c 
            FROM Room__c 
            WHERE Parent_Room__c != NULL 
            AND (Sex__c = :studentGender OR Sex__c = NULL) 
            AND Available_Places__c > 0
            ORDER BY Available_Places__c ASC
            LIMIT :pageSize OFFSET :offset
        ]);

        Set<Id> parentRoomsIds = new Set<Id>();
        for (Room__c childRoom : childRooms.values()) {
            parentRoomsIds.add(childRoom.Parent_Room__c);
        }

        Integer remaining = pageSize - childRooms.keySet().size();
        List<Room__c> parentRooms = new List<Room__c>();
        if (remaining > 0) {
            parentRooms = [
                SELECT Id, Name, Available_Places__c, Capacity__c, Sex__c, Dormitory__r.Name 
                FROM Room__c 
                WHERE Parent_Room__c = NULL 
                AND Id NOT IN :parentRoomsIds
                AND (Sex__c = :studentGender OR Sex__c = NULL) 
                AND Available_Places__c > 0
                ORDER BY Available_Places__c ASC
                LIMIT :remaining OFFSET :offset
            ];
        }

        List<Room__c> availableRooms = new List<Room__c>();
        availableRooms.addAll(childRooms.values());
        availableRooms.addAll(parentRooms);

        return availableRooms;
    }

    @AuraEnabled
    public static Integer getTotalRoomsCount(String studentGender) {
        Integer count = [
            SELECT COUNT()
            FROM Room__c
            WHERE (Sex__c = :studentGender OR Sex__c = NULL)
            AND Available_Places__c > 0
        ];
        return count;
    }
}