force-app/main/default/objects/Contact/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Комната</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Студенты</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dormitory__c/Dormitory__c.object-meta.xml
<CustomObject>
    <label>Общежитие</label>
    <nameField>
        <label>Название общежития</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Общежития</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Мероприятие</label>
    <nameField>
        <label>Название мероприятия</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Мероприятия</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Dormitory__c.field-meta.xml
<CustomField>
    <fullName>Dormitory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Общежитие</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Мероприятия</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Event_DateTime__c</fullName>
    <label>Дата мероприятия</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Place__c.field-meta.xml
<CustomField>
    <fullName>Event_Place__c</fullName>
    <label>Место проведения</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Max_Students__c.field-meta.xml
<CustomField>
    <fullName>Max_Students__c</fullName>
    <label>Максимальное число студентов</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Request__c/Event_Request__c.object-meta.xml
<CustomObject>
    <label>Заявка на мероприятие</label>
    <nameField>
        <displayFormat>ER-{0000}</displayFormat>
        <label>Имя записи</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Заявки на мероприятие</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Request__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Мероприятие</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Заявки на мероприятие</relationshipLabel>
    <relationshipName>Event_Requests</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Комната</label>
    <nameField>
        <label>Номер комнаты</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Комнаты</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Dormitory__c.field-meta.xml
<CustomField>
    <fullName>Dormitory__c</fullName>
    <label>Общежитие</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Комнаты</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventController.cls
public without sharing class EventController {
    @AuraEnabled
    public static List<Event__c> getAvailableDormitoryEvents() {
        Contact studentContact = StudentDAO.getCurrentUserContact();
        //TODO add filtering by study year as with ОПТ
        List<Event__c> dormitoryEvents = [
            SELECT Id, Name, Event_DateTime__c, Max_Students__c, Event_Place__c, Dormitory__c
            FROM Event__c
            WHERE Dormitory__c = :studentContact.Room__r.Dormitory__c
        ];

        return dormitoryEvents;
    }

    @AuraEnabled
    public static List<Event_Request__c> getStudentEventRequests() {
        Contact studentContact = StudentDAO.getCurrentUserContact();

        List<Event_Request__c> studentRequests = [
            SELECT Id, Name,
                Event__r.Name, Event__r.Event_DateTime__c
            FROM Event_Request__c
            WHERE Student_Contact__c = :studentContact.Id
        ];

        return studentRequests;
    }
}