force-app/main/default/objects/Accomodation_Request__c/Accomodation_Request__c.object-meta.xml
<CustomObject>
    <label>Заявка на заселение</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Имя записи</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Заявки на заселение</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accomodation_Request__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Студент</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Заявки на заселение</relationshipLabel>
    <relationshipName>Accomodation_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/StudentDAO.cls
public without sharing class StudentDAO {
    public static Account getAccountById(Id accountId) {
        List<Account> accounts = [
            SELECT Id, PersonContact.Sex__c
            FROM Account
            WHERE Id = :accountId
            LIMIT 1
        ];

        if (!accounts.isEmpty()) {
            return accounts[0];
        }

        return null;
    }

    @AuraEnabled
    public static Account getAccountByAccomodationRequestId(Id requestId) {
        List<Account> accounts = [
            SELECT Id, PersonContact.Sex__c
            FROM Account
            WHERE Id IN (SELECT Student__c FROM Accomodation_Request__c WHERE Id = :requestId)
            LIMIT 1
        ];

        if (!accounts.isEmpty()) {
            return accounts[0];
        }

        return null;
    }
}