force-app/main/default/objects/Accomodation_Request__c/Accomodation_Request__c.object-meta.xml
<CustomObject>
    <label>Заявка на заселение</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Имя записи</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Заявки на заселение</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accomodation_Request__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Комната</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Заявки на заселение</relationshipLabel>
    <relationshipName>Accomodation_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accomodation_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Статус</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Подана</fullName>
            </value>
            <value>
                <fullName>Документы приняты</fullName>
            </value>
            <value>
                <fullName>Одобрена</fullName>
            </value>
            <value>
                <fullName>Заселен</fullName>
            </value>
            <value>
                <fullName>Отклонена</fullName>
            </value>
            <value>
                <fullName>Отменена</fullName>
            </value>
            <value>
                <fullName>Выселен</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Accomodation_Request__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Студент</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Заявки на заселение</relationshipLabel>
    <relationshipName>Accomodation_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Комната</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Студенты</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Пол</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Комната</label>
    <nameField>
        <label>Номер комнаты</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Комнаты</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Available_Places__c.field-meta.xml
<CustomField>
    <fullName>Available_Places__c</fullName>
    <label>Доступно мест</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Пол жильцов</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sexes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccomodationRequestController.cls
public without sharing class AccomodationRequestController {
    @AuraEnabled
    public static Id createAccommodationRequest() {
        try {
            if (!isRegistrationAvailable() || !isRequestSubmissionAvailable()) {
                throw new AccomodationRequestException('You cannot submit request at the moment.');
            }

            Account studentAccount = StudentDAO.getCurrentUserAccount();

            if (studentAccount == null) {
                throw new AccomodationRequestException('No associated Person Account found.');
            }

            Accomodation_Request__c newRequest = new Accomodation_Request__c(
                Student__c = studentAccount.Id,
                Status__c = 'Подана'
            );

            insert newRequest;

            return newRequest.Id;
        } catch (Exception e) {
            LOGGER.error('Error creating request: ' + e.getMessage());
            LOGGER.saveLog();
            throw new AccomodationRequestException('Error creating request: ' + e.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<Accomodation_Request__c> getStudentRequests() {
        try {
            Account studentAccount = StudentDAO.getCurrentUserAccount();

            return [
                SELECT Id, Name, CreatedDate, toLabel(Status__c), Room__c
                FROM Accomodation_Request__c
                WHERE Student__c = :studentAccount.Id
                ORDER BY CreatedDate DESC
            ];
        } catch (Exception e) {
            LOGGER.error('Error fetching student requests: ' + e.getMessage());
            LOGGER.saveLog();
            throw new AccomodationRequestException('Error fetching student requests.');
        }
    }

    @AuraEnabled
    public static Boolean isRegistrationAvailable() {
        return AccomodationSettingsController.getRegistrationStatus();
    }

    @AuraEnabled
    public static Boolean isRequestSubmissionAvailable() {
        Account studentAccount = StudentDAO.getCurrentUserAccount();

        List<Accomodation_Request__c> requests = [
            SELECT Id, Name, CreatedDate, Status__c, Room__c
            FROM Accomodation_Request__c
            WHERE Student__c = :studentAccount.Id AND Status__c IN ('Одобрена', 'Документы приняты', 'Подана')
        ];

        if (!requests.isEmpty()) {
            return false;
        }

        return true;
    }

    @AuraEnabled
    public static void cancelRequest(Id requestId) {
        try {
            Accomodation_Request__c request = [
                SELECT Id, Status__c FROM Accomodation_Request__c WHERE Id = :requestId LIMIT 1
            ];

            if (request.Status__c == 'Отменена') {
                throw new AccomodationRequestException('Заявка уже отменена.');
            }

            if (request.Status__c == 'Подана') {
                throw new AccomodationRequestException('Заявка уже обрабатывается, для её отмены обратитесь в деканат.');
            }

            request.Status__c = 'Отменена';
            update request;
        } catch (Exception e) {
            throw new AccomodationRequestException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void updateAccomodationRequestRoom(Id requestId, Id roomId) {
        try {
            Account studentAccount = StudentDAO.getAccountByAccomodationRequestId(requestId);
            if (studentAccount == null) {
                throw new AccomodationRequestException('Student not found for the request.');
            }

            Room__c selectedRoom = [
                SELECT Id, Available_Places__c, Sex__c
                FROM Room__c
                WHERE Id = :roomId
                LIMIT 1
            ];

            if (selectedRoom.Available_Places__c == null || selectedRoom.Available_Places__c <= 0) {
                throw new AccomodationRequestException('В выбранной комнате нет свободных мест.');
            }

            if (selectedRoom.Sex__c != null && selectedRoom.Sex__c != studentAccount.PersonContact.Sex__c) {
                throw new AccomodationRequestException('Выбранная комната не соответствует полу студента.');
            }

            Accomodation_Request__c request = [
                SELECT Id, Status__c, Room__c
                FROM Accomodation_Request__c
                WHERE Id = :requestId
                LIMIT 1
            ];

            request.Room__c = roomId;
            request.Status__c = 'Заселен';

            Contact studentContact = [
                SELECT Id, Room__c
                FROM Contact
                WHERE AccountId = :studentAccount.Id
                LIMIT 1
            ];
            studentContact.Room__c = roomId;

            selectedRoom.Available_Places__c -= 1;

            update new List<SObject> { request, studentContact, selectedRoom };

        } catch (Exception e) {
            throw new AccomodationRequestException('Ошибка при заселении: ' + e.getMessage());
        }
    }

    public class AccomodationRequestException extends Exception {}
}